name: Trigger auto deployment for overleaf

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/overleaf-AutoDeployTrigger-d87fc5c7-63af-4c3b-a752-65e5ec8b9a26.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.OVERLEAF_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.OVERLEAF_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.OVERLEAF_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: server-ce/Dockerfile
          registryUrl: ${{ secrets.OVERLEAF_REGISTRY_URL }}
          registryUsername: ${{ secrets.OVERLEAF_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.OVERLEAF_REGISTRY_PASSWORD }}
          containerAppName: overleaf
          resourceGroup: agenti-copilot
          imageToBuild: default/overleaf:${{ github.sha }}


